"""Add IB models (precedents, comps, advisors, filings, rumors, pitches, comments, saved filters/dashboards)

Revision ID: a8334ae5e249
Revises: 1e95b2e14598
Create Date: 2025-08-19 09:34:30.960460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8334ae5e249'
down_revision: Union[str, Sequence[str], None] = '1e95b2e14598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_advisors_id'), 'advisors', ['id'], unique=False)
    op.create_index('ix_advisors_name', 'advisors', ['name'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_author', 'comments', ['author'], unique=False)
    op.create_index('ix_comments_created_at', 'comments', ['created_at'], unique=False)
    op.create_index('ix_comments_entity', 'comments', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_table('filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('filed_at', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('highlights_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_filings_filed_at', 'filings', ['filed_at'], unique=False)
    op.create_index(op.f('ix_filings_id'), 'filings', ['id'], unique=False)
    op.create_index('ix_filings_ticker', 'filings', ['ticker'], unique=False)
    op.create_index('ix_filings_ticker_type', 'filings', ['ticker', 'type'], unique=False)
    op.create_index('ix_filings_type', 'filings', ['type'], unique=False)
    op.create_table('pitches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('probability', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pitches_id'), 'pitches', ['id'], unique=False)
    op.create_index('ix_pitches_owner', 'pitches', ['owner'], unique=False)
    op.create_index('ix_pitches_probability', 'pitches', ['probability'], unique=False)
    op.create_index('ix_pitches_sector', 'pitches', ['sector'], unique=False)
    op.create_index('ix_pitches_stage', 'pitches', ['stage'], unique=False)
    op.create_table('precedent_deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acquirer', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('announced_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('ev', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ev_to_revenue', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ev_to_ebitda', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('premium', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('advisors_buy', sa.Text(), nullable=True),
    sa.Column('advisors_sell', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_precedent_deals_announced', 'precedent_deals', ['announced_at'], unique=False)
    op.create_index('ix_precedent_deals_closed', 'precedent_deals', ['closed_at'], unique=False)
    op.create_index('ix_precedent_deals_ev', 'precedent_deals', ['ev'], unique=False)
    op.create_index(op.f('ix_precedent_deals_id'), 'precedent_deals', ['id'], unique=False)
    op.create_index('ix_precedent_deals_region', 'precedent_deals', ['region'], unique=False)
    op.create_index('ix_precedent_deals_sector', 'precedent_deals', ['sector'], unique=False)
    op.create_index('ix_precedent_deals_status', 'precedent_deals', ['status'], unique=False)
    op.create_table('rumors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_ticker', sa.String(), nullable=False),
    sa.Column('counterparty', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('noted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rumors_confidence', 'rumors', ['confidence'], unique=False)
    op.create_index(op.f('ix_rumors_id'), 'rumors', ['id'], unique=False)
    op.create_index('ix_rumors_noted_at', 'rumors', ['noted_at'], unique=False)
    op.create_index('ix_rumors_sector', 'rumors', ['sector'], unique=False)
    op.create_index('ix_rumors_subject', 'rumors', ['subject_ticker'], unique=False)
    op.create_table('saved_dashboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('widgets_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_dashboards_id'), 'saved_dashboards', ['id'], unique=False)
    op.create_index('ix_saved_dashboards_user', 'saved_dashboards', ['user_id'], unique=False)
    op.create_table('saved_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_filters_id'), 'saved_filters', ['id'], unique=False)
    op.create_index('ix_saved_filters_kind', 'saved_filters', ['kind'], unique=False)
    op.create_index('ix_saved_filters_user', 'saved_filters', ['user_id'], unique=False)
    op.create_index('ix_saved_filters_user_kind', 'saved_filters', ['user_id', 'kind'], unique=False)
    op.create_table('advisor_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advisor_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('deal_count', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['advisors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_advisor_stats_advisor_period', 'advisor_stats', ['advisor_id', 'period'], unique=False)
    op.create_index(op.f('ix_advisor_stats_id'), 'advisor_stats', ['id'], unique=False)
    op.create_index('ix_advisor_stats_period', 'advisor_stats', ['period'], unique=False)
    op.create_index('ix_advisor_stats_sector', 'advisor_stats', ['sector'], unique=False)
    op.create_table('comps_peers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('peer_ticker', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comps_peers_company', 'comps_peers', ['company_id'], unique=False)
    op.create_index(op.f('ix_comps_peers_id'), 'comps_peers', ['id'], unique=False)
    op.create_index('ix_comps_peers_ticker', 'comps_peers', ['peer_ticker'], unique=False)
    op.create_table('insider_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('insider_name', sa.String(), nullable=False),
    sa.Column('insider_title', sa.String(), nullable=True),
    sa.Column('insider_relationship', sa.String(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('shares_transacted', sa.Integer(), nullable=False),
    sa.Column('transaction_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('transaction_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('shares_owned_after', sa.Integer(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('form_type', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insider_transactions_company_id', 'insider_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_insider_transactions_id'), 'insider_transactions', ['id'], unique=False)
    op.create_index('ix_insider_transactions_insider_name', 'insider_transactions', ['insider_name'], unique=False)
    op.create_index('ix_insider_transactions_transaction_date', 'insider_transactions', ['transaction_date'], unique=False)
    op.create_index('ix_insider_transactions_transaction_type', 'insider_transactions', ['transaction_type'], unique=False)
    op.create_table('institutional_ownership',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('holder_name', sa.String(), nullable=False),
    sa.Column('holder_type', sa.String(), nullable=True),
    sa.Column('shares_held', sa.Integer(), nullable=False),
    sa.Column('percentage_owned', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('shares_change', sa.Integer(), nullable=True),
    sa.Column('percentage_change', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_institutional_ownership_company_id', 'institutional_ownership', ['company_id'], unique=False)
    op.create_index('ix_institutional_ownership_company_report', 'institutional_ownership', ['company_id', 'report_date'], unique=False)
    op.create_index('ix_institutional_ownership_holder_name', 'institutional_ownership', ['holder_name'], unique=False)
    op.create_index(op.f('ix_institutional_ownership_id'), 'institutional_ownership', ['id'], unique=False)
    op.create_index('ix_institutional_ownership_report_date', 'institutional_ownership', ['report_date'], unique=False)
    op.create_table('deal_timeline',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_title', sa.String(), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('importance_level', sa.String(), nullable=True),
    sa.Column('is_milestone', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deal_timeline_deal_id', 'deal_timeline', ['deal_id'], unique=False)
    op.create_index('ix_deal_timeline_event_date', 'deal_timeline', ['event_date'], unique=False)
    op.create_index('ix_deal_timeline_event_type', 'deal_timeline', ['event_type'], unique=False)
    op.create_index(op.f('ix_deal_timeline_id'), 'deal_timeline', ['id'], unique=False)
    op.create_index('ix_deal_timeline_is_milestone', 'deal_timeline', ['is_milestone'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_index('ix_deal_timeline_is_milestone', table_name='deal_timeline')
    op.drop_index(op.f('ix_deal_timeline_id'), table_name='deal_timeline')
    op.drop_index('ix_deal_timeline_event_type', table_name='deal_timeline')
    op.drop_index('ix_deal_timeline_event_date', table_name='deal_timeline')
    op.drop_index('ix_deal_timeline_deal_id', table_name='deal_timeline')
    op.drop_table('deal_timeline')
    op.drop_index('ix_institutional_ownership_report_date', table_name='institutional_ownership')
    op.drop_index(op.f('ix_institutional_ownership_id'), table_name='institutional_ownership')
    op.drop_index('ix_institutional_ownership_holder_name', table_name='institutional_ownership')
    op.drop_index('ix_institutional_ownership_company_report', table_name='institutional_ownership')
    op.drop_index('ix_institutional_ownership_company_id', table_name='institutional_ownership')
    op.drop_table('institutional_ownership')
    op.drop_index('ix_insider_transactions_transaction_type', table_name='insider_transactions')
    op.drop_index('ix_insider_transactions_transaction_date', table_name='insider_transactions')
    op.drop_index('ix_insider_transactions_insider_name', table_name='insider_transactions')
    op.drop_index(op.f('ix_insider_transactions_id'), table_name='insider_transactions')
    op.drop_index('ix_insider_transactions_company_id', table_name='insider_transactions')
    op.drop_table('insider_transactions')
    op.drop_index('ix_comps_peers_ticker', table_name='comps_peers')
    op.drop_index(op.f('ix_comps_peers_id'), table_name='comps_peers')
    op.drop_index('ix_comps_peers_company', table_name='comps_peers')
    op.drop_table('comps_peers')
    op.drop_index('ix_advisor_stats_sector', table_name='advisor_stats')
    op.drop_index('ix_advisor_stats_period', table_name='advisor_stats')
    op.drop_index(op.f('ix_advisor_stats_id'), table_name='advisor_stats')
    op.drop_index('ix_advisor_stats_advisor_period', table_name='advisor_stats')
    op.drop_table('advisor_stats')
    op.drop_index('ix_saved_filters_user_kind', table_name='saved_filters')
    op.drop_index('ix_saved_filters_user', table_name='saved_filters')
    op.drop_index('ix_saved_filters_kind', table_name='saved_filters')
    op.drop_index(op.f('ix_saved_filters_id'), table_name='saved_filters')
    op.drop_table('saved_filters')
    op.drop_index('ix_saved_dashboards_user', table_name='saved_dashboards')
    op.drop_index(op.f('ix_saved_dashboards_id'), table_name='saved_dashboards')
    op.drop_table('saved_dashboards')
    op.drop_index('ix_rumors_subject', table_name='rumors')
    op.drop_index('ix_rumors_sector', table_name='rumors')
    op.drop_index('ix_rumors_noted_at', table_name='rumors')
    op.drop_index(op.f('ix_rumors_id'), table_name='rumors')
    op.drop_index('ix_rumors_confidence', table_name='rumors')
    op.drop_table('rumors')
    op.drop_index('ix_precedent_deals_status', table_name='precedent_deals')
    op.drop_index('ix_precedent_deals_sector', table_name='precedent_deals')
    op.drop_index('ix_precedent_deals_region', table_name='precedent_deals')
    op.drop_index(op.f('ix_precedent_deals_id'), table_name='precedent_deals')
    op.drop_index('ix_precedent_deals_ev', table_name='precedent_deals')
    op.drop_index('ix_precedent_deals_closed', table_name='precedent_deals')
    op.drop_index('ix_precedent_deals_announced', table_name='precedent_deals')
    op.drop_table('precedent_deals')
    op.drop_index('ix_pitches_stage', table_name='pitches')
    op.drop_index('ix_pitches_sector', table_name='pitches')
    op.drop_index('ix_pitches_probability', table_name='pitches')
    op.drop_index('ix_pitches_owner', table_name='pitches')
    op.drop_index(op.f('ix_pitches_id'), table_name='pitches')
    op.drop_table('pitches')
    op.drop_index('ix_filings_type', table_name='filings')
    op.drop_index('ix_filings_ticker_type', table_name='filings')
    op.drop_index('ix_filings_ticker', table_name='filings')
    op.drop_index(op.f('ix_filings_id'), table_name='filings')
    op.drop_index('ix_filings_filed_at', table_name='filings')
    op.drop_table('filings')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_index('ix_comments_entity', table_name='comments')
    op.drop_index('ix_comments_created_at', table_name='comments')
    op.drop_index('ix_comments_author', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_advisors_name', table_name='advisors')
    op.drop_index(op.f('ix_advisors_id'), table_name='advisors')
    op.drop_table('advisors')
    # ### end Alembic commands ###
