"""bootstrap schema

Revision ID: af068037dbcc
Revises: 
Create Date: 2025-08-17 19:07:52.356449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af068037dbcc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('headquarters', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index('ix_companies_industry', 'companies', ['industry'], unique=False)
    op.create_index('ix_companies_market_cap', 'companies', ['market_cap'], unique=False)
    op.create_index('ix_companies_sector', 'companies', ['sector'], unique=False)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('api_keys', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('deals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deal_type', sa.Enum('ACQUISITION', 'MERGER', 'SPIN_OFF', 'DIVESTITURE', 'JOINT_VENTURE', 'TAKE_PRIVATE', name='dealtype'), nullable=False),
    sa.Column('status', sa.Enum('ANNOUNCED', 'PENDING_REGULATORY', 'REGULATORY_APPROVED', 'COMPLETED', 'TERMINATED', 'WITHDRAWN', name='dealstatus'), nullable=True),
    sa.Column('acquirer_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('deal_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('enterprise_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('equity_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('premium_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('revenue_multiple', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ebitda_multiple', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('payment_type', sa.Enum('CASH', 'STOCK', 'MIXED', 'OTHER', name='paymenttype'), nullable=True),
    sa.Column('cash_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('stock_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('debt_assumed', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('announced_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_close_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('strategic_rationale', sa.Text(), nullable=True),
    sa.Column('cost_synergies', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('revenue_synergies', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('regulatory_approvals_required', sa.Boolean(), nullable=True),
    sa.Column('antitrust_concerns', sa.Boolean(), nullable=True),
    sa.Column('regulatory_notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('is_hostile', sa.Boolean(), nullable=True),
    sa.Column('is_cross_border', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['acquirer_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deals_acquirer_id', 'deals', ['acquirer_id'], unique=False)
    op.create_index('ix_deals_announced_date', 'deals', ['announced_date'], unique=False)
    op.create_index('ix_deals_deal_type', 'deals', ['deal_type'], unique=False)
    op.create_index('ix_deals_deal_value', 'deals', ['deal_value'], unique=False)
    op.create_index(op.f('ix_deals_id'), 'deals', ['id'], unique=False)
    op.create_index('ix_deals_is_active', 'deals', ['is_active'], unique=False)
    op.create_index('ix_deals_status', 'deals', ['status'], unique=False)
    op.create_index('ix_deals_target_id', 'deals', ['target_id'], unique=False)
    op.create_table('financial_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('operating_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('eps_basic', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('eps_diluted', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_equity', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cash_and_equivalents', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('working_capital', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('operating_cash_flow', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('capex', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('current_ratio', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('roe', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('roa', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('operating_margin', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('net_margin', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_financial_metrics_company_id', 'financial_metrics', ['company_id'], unique=False)
    op.create_index('ix_financial_metrics_company_period', 'financial_metrics', ['company_id', 'period_end_date'], unique=False)
    op.create_index('ix_financial_metrics_fiscal_year', 'financial_metrics', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_financial_metrics_id'), 'financial_metrics', ['id'], unique=False)
    op.create_index('ix_financial_metrics_period_end', 'financial_metrics', ['period_end_date'], unique=False)
    op.create_table('market_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('adjusted_close', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('dollar_volume', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('sma_20', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sma_50', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sma_200', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rsi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('shares_outstanding', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('is_adjusted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_data_company_date', 'market_data', ['company_id', 'date'], unique=False)
    op.create_index('ix_market_data_company_id', 'market_data', ['company_id'], unique=False)
    op.create_index('ix_market_data_date', 'market_data', ['date'], unique=False)
    op.create_index(op.f('ix_market_data_id'), 'market_data', ['id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('added_reason', sa.Text(), nullable=True),
    sa.Column('target_price', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('price_alerts_enabled', sa.Boolean(), nullable=True),
    sa.Column('news_alerts_enabled', sa.Boolean(), nullable=True),
    sa.Column('ma_alerts_enabled', sa.Boolean(), nullable=True),
    sa.Column('earnings_alerts_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_user_company_watchlist')
    )
    op.create_index('ix_watchlists_company_id', 'watchlists', ['company_id'], unique=False)
    op.create_index(op.f('ix_watchlists_id'), 'watchlists', ['id'], unique=False)
    op.create_index('ix_watchlists_is_active', 'watchlists', ['is_active'], unique=False)
    op.create_index('ix_watchlists_user_id', 'watchlists', ['user_id'], unique=False)
    op.create_table('ai_insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('deal_id', sa.String(), nullable=True),
    sa.Column('insight_type', sa.Enum('COMPANY_ANALYSIS', 'DEAL_ANALYSIS', 'MARKET_COMMENTARY', 'ALERT_EXPLANATION', 'TREND_ANALYSIS', 'RISK_ASSESSMENT', 'VALUATION_ANALYSIS', 'SECTOR_OVERVIEW', name='insighttype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('full_analysis', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.Column('validation_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('user_feedback', sa.String(), nullable=True),
    sa.Column('is_time_sensitive', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('relevance_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_insights_company_id', 'ai_insights', ['company_id'], unique=False)
    op.create_index('ix_ai_insights_confidence_score', 'ai_insights', ['confidence_score'], unique=False)
    op.create_index('ix_ai_insights_created_at', 'ai_insights', ['created_at'], unique=False)
    op.create_index('ix_ai_insights_deal_id', 'ai_insights', ['deal_id'], unique=False)
    op.create_index(op.f('ix_ai_insights_id'), 'ai_insights', ['id'], unique=False)
    op.create_index('ix_ai_insights_insight_type', 'ai_insights', ['insight_type'], unique=False)
    op.create_index('ix_ai_insights_is_active', 'ai_insights', ['is_active'], unique=False)
    op.create_index('ix_ai_insights_is_featured', 'ai_insights', ['is_featured'], unique=False)
    op.create_index('ix_ai_insights_user_id', 'ai_insights', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('deal_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('PRICE', 'EARNINGS', 'MA', 'NEWS', 'REGULATORY', 'TECHNICAL', 'VOLUME', 'CUSTOM', name='alertcategory'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertseverity'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'TRIGGERED', 'SNOOZED', 'DISMISSED', 'EXPIRED', name='alertstatus'), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('trigger_value', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('push_sent', sa.Boolean(), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_category', 'alerts', ['category'], unique=False)
    op.create_index('ix_alerts_company_id', 'alerts', ['company_id'], unique=False)
    op.create_index('ix_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_deal_id', 'alerts', ['deal_id'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index('ix_alerts_is_read', 'alerts', ['is_read'], unique=False)
    op.create_index('ix_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_triggered_at', 'alerts', ['triggered_at'], unique=False)
    op.create_index('ix_alerts_user_id', 'alerts', ['user_id'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('deal_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('sentiment_label', sa.String(), nullable=True),
    sa.Column('relevance_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('impact_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('duplicate_of', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of'], ['news_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_news_items_category', 'news_items', ['category'], unique=False)
    op.create_index('ix_news_items_company_id', 'news_items', ['company_id'], unique=False)
    op.create_index('ix_news_items_deal_id', 'news_items', ['deal_id'], unique=False)
    op.create_index(op.f('ix_news_items_id'), 'news_items', ['id'], unique=False)
    op.create_index('ix_news_items_published_at', 'news_items', ['published_at'], unique=False)
    op.create_index('ix_news_items_sentiment_score', 'news_items', ['sentiment_score'], unique=False)
    op.create_index('ix_news_items_source', 'news_items', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_news_items_source', table_name='news_items')
    op.drop_index('ix_news_items_sentiment_score', table_name='news_items')
    op.drop_index('ix_news_items_published_at', table_name='news_items')
    op.drop_index(op.f('ix_news_items_id'), table_name='news_items')
    op.drop_index('ix_news_items_deal_id', table_name='news_items')
    op.drop_index('ix_news_items_company_id', table_name='news_items')
    op.drop_index('ix_news_items_category', table_name='news_items')
    op.drop_table('news_items')
    op.drop_index('ix_alerts_user_id', table_name='alerts')
    op.drop_index('ix_alerts_triggered_at', table_name='alerts')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_severity', table_name='alerts')
    op.drop_index('ix_alerts_is_read', table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index('ix_alerts_deal_id', table_name='alerts')
    op.drop_index('ix_alerts_created_at', table_name='alerts')
    op.drop_index('ix_alerts_company_id', table_name='alerts')
    op.drop_index('ix_alerts_category', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_ai_insights_user_id', table_name='ai_insights')
    op.drop_index('ix_ai_insights_is_featured', table_name='ai_insights')
    op.drop_index('ix_ai_insights_is_active', table_name='ai_insights')
    op.drop_index('ix_ai_insights_insight_type', table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_id'), table_name='ai_insights')
    op.drop_index('ix_ai_insights_deal_id', table_name='ai_insights')
    op.drop_index('ix_ai_insights_created_at', table_name='ai_insights')
    op.drop_index('ix_ai_insights_confidence_score', table_name='ai_insights')
    op.drop_index('ix_ai_insights_company_id', table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_index('ix_watchlists_user_id', table_name='watchlists')
    op.drop_index('ix_watchlists_is_active', table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_id'), table_name='watchlists')
    op.drop_index('ix_watchlists_company_id', table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_market_data_id'), table_name='market_data')
    op.drop_index('ix_market_data_date', table_name='market_data')
    op.drop_index('ix_market_data_company_id', table_name='market_data')
    op.drop_index('ix_market_data_company_date', table_name='market_data')
    op.drop_table('market_data')
    op.drop_index('ix_financial_metrics_period_end', table_name='financial_metrics')
    op.drop_index(op.f('ix_financial_metrics_id'), table_name='financial_metrics')
    op.drop_index('ix_financial_metrics_fiscal_year', table_name='financial_metrics')
    op.drop_index('ix_financial_metrics_company_period', table_name='financial_metrics')
    op.drop_index('ix_financial_metrics_company_id', table_name='financial_metrics')
    op.drop_table('financial_metrics')
    op.drop_index('ix_deals_target_id', table_name='deals')
    op.drop_index('ix_deals_status', table_name='deals')
    op.drop_index('ix_deals_is_active', table_name='deals')
    op.drop_index(op.f('ix_deals_id'), table_name='deals')
    op.drop_index('ix_deals_deal_value', table_name='deals')
    op.drop_index('ix_deals_deal_type', table_name='deals')
    op.drop_index('ix_deals_announced_date', table_name='deals')
    op.drop_index('ix_deals_acquirer_id', table_name='deals')
    op.drop_table('deals')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index('ix_companies_sector', table_name='companies')
    op.drop_index('ix_companies_market_cap', table_name='companies')
    op.drop_index('ix_companies_industry', table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
